# docker-compose.yml
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: STORE
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 1qaz2wsx
    ports:
      - "5432:5432"
    volumes:
      - store_data:/var/lib/postgresql/data

volumes:
  store_data: