import { Entity, PrimaryGeneratedColumn, Column, OneToMany } from 'typeorm';
import { Store } from '../store/store.entity';

@Entity('Admin')
export class Admin {
  @PrimaryGeneratedColumn()
  id: number;

  //Generated by TRIGGER upon INSERTION
  @Column({ type: 'varchar', length: 5, unique: true, nullable: true }) //Nullable for now
  adminId: string;

  @Column({ type: 'text', unique: true })
  name: string;

  @Column({ type: 'text' })
  officeId: string;

  @OneToMany(() => Store, (store) => store.admin)
  stores: Store[];
}